Add manual analysis of px4 commit 256-265
ciselab/CPS_repo_mining pull request #10
Opened 2021-12-03 20:39 UTC by LHolten

2021-12-07 10:20 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +-
Please add a comment to the note here, a short sentence for this case is fine.

2021-12-07 10:25 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +This commit changes a save function to retry 5 times before giving up.
It seems to me to be a General:Hard_Coded instead of a New:Hard-coded-fine-tuning. Implementing a fixed 5 times retry would fit in the General:Hard_Coded; but if this was adjusted multiple times in the history of the file (for example from 5 tries to 10 tries), it would fit New:Hard-coded-fine-tuning. In that case, this should be described in the Note section.

2021-12-07 10:27 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +X
This change seems to fit the New:Fixed-communication-rate Antipattern.

2021-12-07 10:30 UTC, IvDinten requested changes
See the comments made to the commit analyses of #257, #263 and #264.

2021-12-08 19:35 UTC, LHolten commented
@IvDinten thanks for the feedback, is it better now?

2021-12-14 10:03 UTC, IvDinten approved these changes

2021-12-14 10:04 UTC, merged