Draft: commits 351-380
ciselab/CPS_repo_mining pull request #13
Opened 2021-12-23 12:03 UTC by slmarii

2022-01-24 16:32 UTC, pderakhshanfar requested changes

2022-01-27 15:55 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +Not an anti-pattern.
Alright, I will update the notes. Also, you are right, I misinterpreted the variables used.

2022-01-27 16:20 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +New:Hard-coded-fine-tuning
Yes, I missed that.

2022-01-27 16:47 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +Issue: Log tasks low on stack #5891.
My bad, that's the name of the issue related to the commit. I didn't add an explanation because I wasn't sure if it's Unnecessary_Processing. Also, for Extraneous Fetching, the tag is Smith:General:Extraneous_Fetching?

2022-02-09 15:48 UTC, merged