Manual analysis 301-350 [WIP]
ciselab/CPS_repo_mining pull request #14
Opened 2021-12-26 15:34 UTC by LHolten

For some commits i filled in a question mark for the Category.
After fixing those this pull request will be ready.

2022-01-22 14:11 UTC, LHolten commented
Ready for review

2022-01-24 16:31 UTC, pderakhshanfar requested changes

2022-01-24 16:31 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
> +The number of file descriptors is changed without explanation.
But, do we know if these changes are because of a performance issue?

2022-01-24 16:31 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
> +No anti-pattern was found.
Can you elaborate more about this case?

2022-01-24 16:31 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
> +There is no need to wake up the worker thread if that thread is the current thread.
Isnt it "Smith:General:Unnecessary_Processing"?

2022-02-01 12:12 UTC, LHolten commented on analysis/PX4-Autopilot.md
> +No antipatterns were found.
You may be right, it's hard to tell.

2022-02-01 12:23 UTC, LHolten commented on analysis/PX4-Autopilot.md
> +The number of file descriptors is changed without explanation.
There are no issues related to this commit. Searching for file descriptors turned up this https://github.com/PX4/PX4-Autopilot/issues/14157#issuecomment-588372647. So the commit under analysis was probably also to fix a similar problem.
This leads me to believe it is not a performance anti pattern.

2022-02-01 12:46 UTC, LHolten commented on analysis/PX4-Autopilot.md
> +The number of file descriptors is changed without explanation.
Why would they choose a small number of file descriptors if not for performance?

2022-02-01 12:55 UTC, LHolten commented on analysis/PX4-Autopilot.md
> +No anti-pattern was found.
Done, you can check again.

2022-02-01 12:56 UTC, LHolten commented on analysis/PX4-Autopilot.md
> +There is no need to wake up the worker thread if that thread is the current thread.
Fixed

2022-02-01 12:56 UTC, LHolten commented on analysis/PX4-Autopilot.md
> +General:Unnecessary-processing
Fixed

2022-02-01 12:56 UTC, LHolten commented on analysis/PX4-Autopilot.md
> +Changes the stack size of some tests.
Fixed

2022-02-09 15:37 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
> +The number of file descriptors is changed without explanation.
I see your point here.
can you extend the note and explain that the authors had some discussions about the limited number of file descriptors? and also add the link to the comment

2022-02-25 07:20 UTC, merged