Commits 430-480
ciselab/CPS_repo_mining pull request #15
Opened 2022-01-27 17:33 UTC by slmarii

2022-02-24 14:17 UTC, pderakhshanfar requested changes

2022-02-24 14:17 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
> +Max bytes sent increased from 64 * 1024 to 256 * 1024.
I think it is Fixed Communication Rate too.

2022-02-24 14:17 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
> +Number of config files increased to 5.
But does thid change leads to any difference in the performance of the system?

2022-02-24 14:17 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
> +Delay increased from 6 to 400.
Isnt it magical waiting number?

2022-02-24 14:17 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
> +Value reduced from 7 to 6.
Value of logger buffer is changed here. Isn't it a regular hard-coded value anti-pattern? I guess there is no hardware involved in the logging.

2022-02-24 14:17 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
> +Timeout increased from 300 ms to 5 s.
It is a magical waiting number. It is related to waiting for task in hardware to be finished.

2022-02-24 18:32 UTC, slmarii commented on analysis/PX4-Autopilot.md
>  Reduces CPU load from ~6.9% to 5.3% (tested on Pixracer & Pixhawk). The
Yes, I didn't realize this when I added the note, although I don't think it's not an anti-pattern, as the function was made inline.

2022-02-24 18:53 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +Value reduced from 7 to 6.
I considered it to be Hard-coded-fine-tuning as the commit mentions that it reduces the memory footprint, a relevant aspect when it comes to the performance of an embedded system.

2022-02-24 18:55 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +Delay increased from 6 to 400.
Yes, it is.

2022-02-24 19:17 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +Number of config files increased to 5.
No, my bad, I mistook it with a similar commit linked to the same issue that simplified the parsing of hardfaults logs.

2022-02-25 07:06 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
> -Number of config files increased to 5.
Empty note

2022-02-25 07:06 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
> -Value decreased from 0.7 to 0.5.
Empty Note. Just add a sentence mentioning that this change does not impact the performance of the system.

2022-02-25 07:06 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
> +Value reduced from 7 to 6.
Yes, it has an impact on the performance of the system. But this is a performance issue happened in the logging. Since any type of system can have a logging process, this performance antipattern is not dedictaed to the CPSs only. So, it cannot be hard-coded-fine-tuning. Instead, we can put sth general (but performance-related) like General:performance:Hard-coding

2022-02-25 07:10 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
>  Reduces CPU load from ~6.9% to 5.3% (tested on Pixracer & Pixhawk). The
True, it is not an antipattern. But, please update the note and mention that this is a performance issue that is onlly applicable in C++ (so, no CPS antipattern).

2022-02-25 15:17 UTC, slmarii commented on analysis/PX4-Autopilot.md
>  Reduces CPU load from ~6.9% to 5.3% (tested on Pixracer & Pixhawk). The
Will do

2022-02-25 15:17 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +Value reduced from 7 to 6.
Alright, thanks for the explanation.

2022-02-25 15:30 UTC, slmarii commented on analysis/PX4-Autopilot.md
> -Number of config files increased to 5.
Added a note

2022-05-03 11:34 UTC, IvDinten commented on analysis/PX4-Autopilot.md
>  Reduces CPU load from ~6.9% to 5.3% (tested on Pixracer & Pixhawk). The
@slmarii maybe add to the note that this is a C++ specific issue? @pderakhshanfar

2022-05-03 11:43 UTC, IvDinten requested changes
As I see, there is only 1 comment open currently. @slmarii please address this one. @pderakhshanfar after this (Change Request) it seems the PR is ready for merge.

2022-05-12 09:38 UTC, slmarii commented on analysis/PX4-Autopilot.md
>  Reduces CPU load from ~6.9% to 5.3% (tested on Pixracer & Pixhawk). The
@IvDinten it should be fixed now.

2022-05-12 11:22 UTC, IvDinten requested changes
Please see the comment regarding the commit # removed, I guess this was done by accident?

2022-05-12 11:22 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> -## Commit #468
@slmarii why did you remove this commit #?

2022-05-12 14:44 UTC, slmarii commented on analysis/PX4-Autopilot.md
> -## Commit #468
Sorry, I am having checkout errors in this branch for some reason and this change didn't show up. Also, I am not entirely sure how these lines got removed.

2022-05-12 14:51 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> -## Commit #468
No problem! That can happen, just wanted to be sure 👍

2022-05-12 14:51 UTC, IvDinten approved these changes

2022-05-12 15:10 UTC, merged