Analysis sm5.1
ciselab/CPS_repo_mining pull request #20
Opened 2022-02-06 15:40 UTC by slmarii

2022-04-25 12:44 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features.
I would argue there are some performance related changes made, just not of interest for this current study. Maybe change the note slightly?

2022-04-25 12:47 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +Value changed from 51 to 54.
The code changes are:
```
- CONFIG_NFILE_DESCRIPTORS=47
+ CONFIG_NFILE_DESCRIPTORS=54
```
Not 51 -> 54 as is written in the note.

Interesting though, the commit message is also incorrect (done by the developer).

2022-04-25 12:49 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +Value changed from 51 to 54.
The code changes are:

```
- CONFIG_NFILE_DESCRIPTORS=53
+ CONFIG_NFILE_DESCRIPTORS=54
```

Not 51 -> 54 as is written in the note.

2022-04-25 13:12 UTC, IvDinten requested changes
Check comments for change requests.

2022-04-29 19:57 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features.
Will do

2022-04-29 20:00 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +Value changed from 51 to 54.
Will update the note

2022-04-29 20:00 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +Value changed from 51 to 54.
Will correct it

2022-05-02 15:25 UTC, IvDinten approved these changes

2022-05-02 15:25 UTC, merged