Commits 532-580
ciselab/CPS_repo_mining pull request #21
Opened 2022-02-08 14:19 UTC by slmarii

2022-04-25 12:55 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +X
Similar change as in commit #516, but a different conclusion? Could you clarify this decision?

2022-04-25 12:56 UTC, IvDinten commented on analysis/PX4-Autopilot.md
>  ## Commit #540
This commit has been forgotten, @slmarii please analyse this commit.

2022-04-25 12:57 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +Stack size increased from 1000 to 1100.
@slmarii This note belongs to #540, so #541 was actually accidentally skipped, not #540.

2022-04-25 13:00 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +_hold_yaw is being used if finite, otherwise constant _yaw.
This note (and thereby this analysis, including Antipattern category) belongs to commit #547, not this one.
This commit has been accidentally skipped. @slmarii please take a look and move this analysis to #547 and analyse #548.

2022-04-25 13:01 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +PWB Default Min increased from 0 to 20.
Also the following change was made:
```
- int poll_ret = px4_poll(fds, 2, 1000);
+ int poll_ret = px4_poll(fds, 2, 500);
```

2022-04-25 13:13 UTC, IvDinten requested changes
Check comments for change requests.

2022-04-29 20:29 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +PWB Default Min increased from 0 to 20.
Will update the notes and Antipattern category sections.

2022-04-29 20:32 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +New:Hard-coded-timing, New:Hard-coded-fine-tuning
Will update the commit

2022-04-29 20:32 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +_hold_yaw is being used if finite, otherwise constant _yaw.
Will correct these mistakes.

2022-04-29 20:33 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +Stack size increased from 1000 to 1100.
Will update the commits

2022-04-29 20:41 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +X
My bad, I got confused about the meaning of pitching for an aircraft and control of roll axis. I will correct this commit.

2022-05-02 15:35 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +New:Hard-coded-timing, New:Hard-coded-fine-tuning
@slmarii It seem that the note for commit #569 was not updated with this change.

2022-05-02 16:20 UTC, IvDinten requested changes
Check comment(s) for change requests.

2022-05-12 09:41 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +New:Hard-coded-timing, New:Hard-coded-fine-tuning
My bad, I pushed another commit now.

2022-05-12 11:34 UTC, IvDinten approved these changes

2022-05-12 11:35 UTC, merged