730-830
ciselab/CPS_repo_mining pull request #22
Opened 2022-02-25 15:09 UTC by slmarii

2022-04-25 15:30 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features.
Gyro cutoff has been decreased, candidate for New:Hard-coded-fine-tuning?
```
- param set IMU_GYRO_CUTOFF 80
- param set IMU_DGYRO_CUTOFF 40
+ param set IMU_GYRO_CUTOFF 60
+ param set IMU_DGYRO_CUTOFF 30
```

2022-04-25 15:32 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +CMake selective optimizations.
Priority change interesting for New:Hard-coded-fine-tuning?
```
- static constexpr wq_config_t attitude_ctrl{"wq:attitude_ctrl", 1536, -13};
+ static constexpr wq_config_t attitude_ctrl{"wq:attitude_ctrl", 1600, -13};
```

2022-04-25 15:37 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features.
```
- PARAM_DEFINE_FLOAT(MPC_LAND_VEL_XY, 2.f);
+ PARAM_DEFINE_FLOAT(MPC_LAND_VEL_XY, 10.0f);
```
New:Hard-coded-fine-tuning?

2022-04-25 15:40 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +X
Would this not be a candidate for the General:Hard-coding?

2022-04-25 15:43 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features. New topics added.
This section looks interesting:
```
- // log all raw sensors at minimal rate (1 Hz)
- add_topic_multi("battery_status", 1000);
+ // log all raw sensors at minimal rate (at least 1 Hz)
+ add_topic_multi("battery_status", 300);
```

2022-04-25 15:48 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +X
Interesting section?
```
PARAM_DEFINE_FLOAT(COM_RC_LOSS_T, 0.5f);
/**
 * RC stick override threshold
 *
 * If an RC stick is moved more than by this amount the system will interpret this as
 * override request by the pilot.
 *
 * @group Commander
 * @unit %
 * @min 5
```
```
- * @max 40
+ * @max 80
```
```
 * @decimal 0
 * @increment 0.05
 */
```
```
- PARAM_DEFINE_FLOAT(COM_RC_STICK_OV, 12.0f);
+ PARAM_DEFINE_FLOAT(COM_RC_STICK_OV, 50.0f);
```

2022-04-25 15:57 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +Stack size increased from 2650 to 2848.
This commit reverts the change, so 2848  -> 2650.

2022-04-25 16:03 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features. Test setup change.
How does this change the test setup?

2022-04-25 16:06 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features.
Potential for New:Hard-coded-fine-tuning?
```
- PARAM_DEFINE_FLOAT(LNDFW_AIRSPD_MAX, 8.00f);
+ PARAM_DEFINE_FLOAT(LNDFW_AIRSPD_MAX, 6.00f);
```

2022-04-25 16:18 UTC, IvDinten requested changes
Check comments for change requests.

2022-04-29 21:22 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features.
Yes, I will update the commit.

2022-04-29 21:24 UTC, slmarii commented on analysis/PX4-Autopilot.md
>  ## Commit #732
My bad, I updated these commits, not sure about 733

2022-04-29 21:41 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features.
Not sure about this one, the change is best described here:
"Set the ground slow down speed to the default maximum speed. This results in no change with defaults but a slow down to 10m/s if the maximum speed is set higher than that."

2022-04-29 21:48 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +X
I considered that no performance-related feature is changed by this commit, as these hard coded values are used only for printing warnings in case the free stack space is smaller than them.

2022-04-29 21:54 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features. New topics added.
Will update the commit with New:Hard-coded-fine-tuning, New:Hard-coded-timing.

2022-04-29 21:59 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +New:Fixed_Communication_Rate
Yes it is

2022-04-29 22:22 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features. Test setup change.
It doesn't, not sure how it got there. I will update the commit

2022-04-29 22:24 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features.
Yes, I will update the commit

2022-04-29 22:26 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +New:Fixed_Communication_Rate
I will add it.

2022-05-02 16:01 UTC, IvDinten commented on analysis/PX4-Autopilot.md
>  ## Commit #732
I would say that for "There was bug corrected, where 2 uints were substracted, not sure whether this falls under New:rounded_numbers or another antipattern." it would not fall under New:rounded_numbers. I would also not categorize it under a different antipattern.

2022-05-02 16:11 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features.
@pderakhshanfar could you also take a look at this one? I currently tend to agree that it might not be for New:Hard-coded-fine-tuning.

2022-05-02 16:14 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +X
Good point, I agree.

2022-05-02 16:20 UTC, IvDinten requested changes
Check comment(s) for change requests.

2022-05-03 15:50 UTC, pderakhshanfar commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features.
I dont think this is a hard-coded fine tuning. This change prevents the landing speed from exceeding a threshold.

2022-05-03 16:07 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +This commit does not change any performance-related features.
Resolving the conversation 👍

2022-05-12 09:46 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +X
Will update the commit

2022-05-12 09:46 UTC, slmarii commented on analysis/PX4-Autopilot.md
>  ## Commit #732
I will update the commit

2022-05-12 11:48 UTC, IvDinten requested changes
See comment for commit #768.

2022-05-12 11:48 UTC, IvDinten commented on analysis/PX4-Autopilot.md
> +Override threshold for the RC stick increased from 12 to 15.
@slmarii the overwrite is from 12 to 50.

2022-05-12 14:30 UTC, slmarii commented on analysis/PX4-Autopilot.md
> +Override threshold for the RC stick increased from 12 to 15.
Sorry!

2022-05-12 14:58 UTC, IvDinten approved these changes

2022-05-12 14:58 UTC, merged