new batch 0-43
ciselab/CPS_repo_mining pull request #26
Opened 2022-03-27 17:16 UTC by slmarii

2022-04-25 16:56 UTC, IvDinten commented on analysis/arduino_esp32.md
> +Deadlock error.
Maybe update the note to: Fix for deadlock error.

2022-04-25 16:57 UTC, IvDinten commented on analysis/arduino_esp32.md
> +This commit does not change any performance-related features. Delay added before detaching the device.
Would this not be a New:Hard-coded-timing antipattern?

2022-04-25 16:58 UTC, IvDinten requested changes
Check comments for change requests.

2022-05-12 10:02 UTC, slmarii commented on analysis/arduino_esp32.md
> +Deadlock error.
Alright

2022-05-12 14:18 UTC, IvDinten approved these changes

2022-05-12 14:18 UTC, merged