Commits 0-63 grbl
ciselab/CPS_repo_mining pull request #27
Opened 2022-04-18 12:48 UTC by slmarii

2022-04-25 17:15 UTC, IvDinten commented on analysis/grbl.md
> +Computational overhead reduced by simplifying expensive mathematical operations, not sure whether this classifies as Smith:General:Unnecessary_Processing.
@pderakhshanfar What do you think?

2022-04-25 17:19 UTC, IvDinten commented on analysis/grbl.md
> +This commit does not change any performance-related features.
Interesting part for New:Hard-coded-timing?
```
// NOTE: If set to zero, the delay will not be compiled.
#define STEPPER_IDLE_LOCK_TIME 25 // (milliseconds) - Integer > 0
```

2022-04-25 17:25 UTC, IvDinten commented on analysis/grbl.md
> +Not sure whether it falls under any category of performance anti-patterns. The improvement comes from parsing the number of decimals with a factor of 2 instead of 1 and printing a char[] instead of e
I think it is a performance improvement, but maybe no antipattern in here. At least not one we currently have in our list. Good to remember though!

2022-04-25 17:31 UTC, IvDinten commented on analysis/grbl.md
> +Not sure if there any antipatterns.
According to the commit message, the code might be buggy. I do not see any of the antipatterns that we are looking for.

2022-04-25 18:51 UTC, IvDinten commented on analysis/grbl.md
> +Frequency increased from 20Hz to 30Hz.
The DEFAULT_RAPID_FEEDRATE and DEFAULT_ACCELERATION  also changed.

2022-04-25 18:56 UTC, IvDinten commented on analysis/grbl.md
> +This commit does not change any performance-related features. Code re-organizations, code cleanup, some pin operations changed.
The DEFAULT_HOMING_SEEK_RATE, would this be interesting for New:Fixed_Communication_Rate or New:Hard-coded-fine-tuning?

2022-04-25 19:03 UTC, IvDinten commented on analysis/grbl.md
> +This commit does not change any performance-related features. Some methods for settings added, readme update.
Some default rates were changed in the defaults.h file. Potential for the New:Hard-coded-fine-tuning?

2022-04-25 19:09 UTC, IvDinten requested changes
Check comments for change requests.

2022-05-03 15:55 UTC, pderakhshanfar commented on analysis/grbl.md
> +Computational overhead reduced by simplifying expensive mathematical operations, not sure whether this classifies as Smith:General:Unnecessary_Processing.
As mentioned in the commit message, they have removed unnecassary calculations (e.g., recalculating **unchanged blocks**). I think this is an Unnecessary_Processing antipattern indeed.

2022-05-03 15:59 UTC, pderakhshanfar commented on analysis/grbl.md
> +This commit does not change any performance-related features. Not sure whether the changes in void delay_us(uint16_t us) improve the performance and not only the accuracy.
I agree with you Imara. I think the change imoroves the performance. and since it makes the delay more accurate, isnt it magical waiting number?

2022-05-03 16:10 UTC, IvDinten commented on analysis/grbl.md
> +This commit does not change any performance-related features. Not sure whether the changes in void delay_us(uint16_t us) improve the performance and not only the accuracy.
Yes, I would also categorize it as Magical Waiting Number.

2022-05-12 10:07 UTC, slmarii commented on analysis/grbl.md
> +Computational overhead reduced by simplifying expensive mathematical operations, not sure whether this classifies as Smith:General:Unnecessary_Processing.
Will update the note

2022-05-12 10:11 UTC, slmarii commented on analysis/grbl.md
> +This commit does not change any performance-related features. Mostly code formatting.
I will add to the notes the fine tuning of buffer block size, but only the documentation was changed for the second part (New:Hard-coded-timing).

2022-05-12 10:22 UTC, slmarii commented on analysis/grbl.md
> +This commit does not change any performance-related features. Code re-organizations, code cleanup, some pin operations changed.
Yes it is

2022-05-12 14:26 UTC, IvDinten commented on analysis/grbl.md
> +Bug fixes, this commit does not change any performance-related features.
@slmarii There are a some minor bug fixes, but mainly newly added features. The commit message stated this code is likely to be buggy, though I did not see any antipatterns that we are looking for.

2022-05-12 14:30 UTC, IvDinten commented on analysis/grbl.md
> +DEFAULT_Z_MAX_RATE increased from 500 to 750 mm/min.
The DEFAULT_Z_MAX_RATE decreased from 750 to 500.
```
-   #define DEFAULT_Z_MAX_RATE 750.0 // mm/min
+  #define DEFAULT_Z_MAX_RATE 500.0 // mm/min
```

2022-05-12 14:39 UTC, slmarii commented on analysis/grbl.md
> +Bug fixes, this commit does not change any performance-related features.
Will mention this in the note

2022-05-12 14:40 UTC, slmarii commented on analysis/grbl.md
> +DEFAULT_Z_MAX_RATE increased from 500 to 750 mm/min.
Will correct this.

2022-05-12 15:01 UTC, merged